### ISSUE TITLE
Missing module When Running Dev Server 

### ISSUE THREAD

**Issue by pllearns** [wespr/truffle-vue#1]
- When executing `npm run dev` compile fails with message: `Cannot find module 'eslint-plugin-babel'`

- There is also lint errors for `./src/js/users.js` 

- Can I submit a pull request for these? Please let me know when you can. Thank you for this truffle box!

**Comment by osarrouy** [comment]
Hi,

That's weird : `babel-eslint` is in the dev-dependencies and this box is supposed to automatically install its dependencies during unboxing ...

I don't have a lint errors either on `./src/js/users.js`.

Can you tell me which version of `npm` you run ? And which version of `eslint-plugin-babel` you installed ?

Let's try to figure this out and then yes, sure, any PR is welcome :)

Thanks for your interest in this box by the way!

**Comment by pllearns** [comment]
Sure! I'm running ` "eslint-plugin-babel": "^4.1.2",` and `npm 5.5.1`. I saw that you have `"npm": ">= 3.0.0"` running in the engines, so I wasn't sure. 
I agree, if we can figure it out, then a PR may be needed. Thanks for responding!

**Comment by osarrouy** [comment]
Thanks!

It seems that `eslint-plugin-babel` is a kind of extension to add linting for babel experimental features. So it's not really needed for this box. It's strange that npm requires its install. :-/

I've just tested with node 5.5.1 and it works great on my config ... I guess it should be a versioning problem with `babel` and `eslint`.

Are all your `babel` and `eslint` package installed locally or are some installed globally ? And which version ?

Any other idea where the problem could come from ?

**Comment by pllearns** [comment]
Hey, apologies for the delay in response. I'm looking into it on my end. When I know more I'll update here. My packages should be local though.

**Comment by osarrouy** [comment]
Great! Tell me when you have something.

**Comment by osarrouy** [comment]
Closing this issue since there's no feedback anymore.
